version: '3.8'

services:
  koha_db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: Yb0Urv9n1f3y6wJt5M4LIES7jAo28eKq
      MYSQL_DATABASE: zeabur
    networks:
      - koha_network

  koha_web:
    image: digibib/koha:latest
    # AQUÍ ESTÁ LA CLAVE: 
    # Movemos el script que causa el error para que Perl no pueda encontrarlo.
    entrypoint: >
      bash -c "rm -f /usr/share/perl5/Net/Stomp.pm && /usr/sbin/apache2ctl -D FOREGROUND"
    environment:
      - KOHA_INSTANCE=digitalgmas
      - KOHA_DBHOST=koha_db
      - KOHA_DBNAME=zeabur
      - KOHA_DBUSER=root
      - KOHA_DBPASS=Yb0Urv9n1f3y6wJt5M4LIES7jAo28eKq
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - koha_db
    networks:
      - koha_network

networks:
  koha_network:
    driver: bridge
